twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'
        - 'bootstrap_5_layout.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - 'form/croppable_image.html.twig'

when@test:
    twig:
        strict_variables: true
